docker-image.yml update test - 19

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -84,40 +84,40 @@ jobs:
           aws-region: ${{ env.AWS_REGION }}
 
       - name: Login to Amazon ECR
-        uses: aws-actions/amazon-ecr-login@v1
+        uses: aws-actions/amazon-ecr-login@v2
 
-#      - name: Cache Docker layers
-#        uses: actions/cache@v4
-#        with:
-#          path: /tmp/.buildx-cache
-#          key: ${{ runner.os }}-buildx-${{ github.sha }}
-#          restore-keys: |
-#              ${{ runner.os }}-buildx-
-#
-#      - name: Build and Push Docker image
-#        run: |
-#              docker buildx create --use
-#              docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache \
-#                                  --cache-to=type=local,dest=/tmp/.buildx-cache \
-#                                  --push \
-#                                  -t ${{ env.ECR_REPO }}:latest .
-#              if [ $? -ne 0 ]; then
-#                echo "Docker push failed"
-#                exit 1
-#              fi
+      - name: Cache Docker layers
+        uses: actions/cache@v4
+        with:
+          path: /tmp/.buildx-cache
+          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          restore-keys: |
+              ${{ runner.os }}-buildx-
+
       - name: Build and Push Docker image
         run: |
-          docker build -t ${{ env.ECR_REPO }}:latest .
-          docker push ${{ env.ECR_REPO }}:latest
+              docker buildx create --use
+              docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache \
+                                  --cache-to=type=local,dest=/tmp/.buildx-cache \
+                                  --output=type=registry \
+                                  -t ${{ env.ECR_REPO }}:latest .
+              if [ $? -ne 0 ]; then
+                echo "Docker push failed"
+                exit 1
+              fi
+#      - name: Build and Push Docker image
+#        run: |
+#          docker build -t ${{ env.ECR_REPO }}:latest .
+#          docker push ${{ env.ECR_REPO }}:latest
       
 
-      - name: Deploy to Lambda
-        if: ${{ vars.UPDATE_LAMBDA == 'true' }}
-        run: |
-          aws lambda update-function-code \
-            --function-name github_pipeline_docker_Img \
-            --image-uri ${{ env.ECR_REPO }}:latest
-          if [ $? -ne 0 ]; then
-            echo "Lambda deployment failed"
-            exit 1
-          fi
+#      - name: Deploy to Lambda
+#        if: ${{ vars.UPDATE_LAMBDA == 'true' }}
+#        run: |
+#          aws lambda update-function-code \
+#            --function-name github_pipeline_docker_Img \
+#            --image-uri ${{ env.ECR_REPO }}:latest
+#          if [ $? -ne 0 ]; then
+#            echo "Lambda deployment failed"
+#            exit 1
+#          fi
